# This is a basic workflow to help you get started with Actions

name: dockerHub CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Install Packages
        run: composer install --no-dev
        working-directory: backend

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the image and push
        run: |
          docker buildx build --push \
            --tag ueniueni/docker-code-server:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
